### ISSUE TITLE
[FEATURE REQUEST] Square shape for joystick movement

### ISSUE THREAD

**Issue by htshah** [yoannmoinet/nipplejs#104]
The current version always creates a circular region for the joystick to move. But, in my use case(Remote Controller for drone), I need a Square region wherein the joystick can move.

**This is what my suggestion is:**
```javascript
var options = {
    ...,
    shape: "circle" || "square",    // Default - circle
    ...,
}
```
**Expected output**
The smaller inner circle should be able to move in a square shaped region

Thank you!!:smile:

**Comment by yoannmoinet** [comment]
Fixed in #107
