### ISSUE TITLE
Use latest commit 

### ISSUE THREAD

**Issue by pircjernej** [yoannmoinet/nipplejs#105]
If I use : npm install nipplejs
I get installed version 0.8.1
But I need fix for typescript ionic:
https://github.com/yoannmoinet/nipplejs/commit/4f1bdbdd8dcd60e549adb830ab2866d99d22c94a
How I can install version with this commit?
Also if is posible : https://github.com/yoannmoinet/nipplejs/pull/96

**Comment by yoannmoinet** [comment]
I've published `0.8.2` which is the latest version and has 4f1bdbd in it.

#96 isn't ok to be merged, so it won't be there since I'm closing it, the author hasn't responded to my comments.

Feel free to have a go at the feature if you want to add it to the lib.
