### ISSUE TITLE
i need c# joystick

### ISSUE THREAD

**Issue by vimevim** [yoannmoinet/nipplejs#108]
I am not very familiar with this javascript, i just searched for a good joystick in C# language which i am making my project with this. Chek my repositories, i am trying to develope a joystick. Help me out pls.

**Comment by yoannmoinet** [comment]
This is not an issue.

**Comment by yoannmoinet** [comment]
If you need more info on how this works, you can have a look in there.
https://github.com/yoannmoinet/nipplejs/blob/master/src/nipple.js#L295-L398
