### ISSUE TITLE
Multiple instances of joystick visible [BUG]

### ISSUE THREAD

**Issue by Petr-Hric** [yoannmoinet/nipplejs#109]
**Bug description**
There is possibility of having multiple joystick instances visible for dynamic joystick demo (see "To Reproduce" section)

**To Reproduce**
1. Press left mouse button to summon (dynamic) joystick (when the cursor is in joystick demo area)
2. Preserve the mouse button pressed and move cursor out of joystick demo area
3. Release the mouse button
4. Press left mouse button to summon (dynamic) joystick (when the cursor is in joystick demo area)
5. You can see, that old joystick is preserved and new one is visible under your cursor

**Expected behavior**
One instance of joystick is visible

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 74.0.3729.169 (Official Build) (64-bit)

**Comment by yoannmoinet** [comment]
I was able to reproduce the issue.
I'll work on it as soon as I have some time.
