### ISSUE TITLE
Reset direction event

### ISSUE THREAD

**Issue by jeremiax** [yoannmoinet/nipplejs#110]
Hello, although I am not a professional programmer, I whould like to thank you for this wonderful piece of code that is nipplejs (with the name included). I don't know if this is a bug or more a feature request. 

I'm not sure but I think it's repeating a behavior very similar to the one expressed in #25, reproducible in your codepen demo. Steps to reproduce it:

- move joystick up => the dir:up event is triggered
- go back to the center (whithout leaving the input over the joystick, no onmouseup, I assume this is achieved going back under the threshold)
- move joystick up again => the dir:up event is NOT triggered (the desired whould be that the dir:up event is triggered again)

This only happens when you try to repeat the direction, if you try any other direction the event is triggered correctly. Is there any way I can achieve this behaviour?

I do not know if this makes sense. Thanks for your help and sorry for the language, I am not native English speaker.

**Comment by yoannmoinet** [comment]
Hi, thanks for the heads-up, I'll have a look as soon as I have some time.
