### ISSUE TITLE
[BUG] lockX / lockY don't lock the angle 

### ISSUE THREAD

**Issue by popoleeMaster** [yoannmoinet/nipplejs#111]
So I made a project, where i locked my nipple into x / y

```
    this.joystickManager = nipplejs.create({
      zone : this.joystick.nativeElement,
      position: {left: '50%', top: '50%'},
      mode: 'semi',
      lockX: true
    });
```

it works nice in the HTML, but the angle/radians are still giving out direction including X and Y.

(demo)
https://stackblitz.com/edit/angular-fazjcf

if the joystick is locked, the angle should also be locked

**Comment by yoannmoinet** [comment]
I see, thanks for the report, I'll check it out once I have some time.
