### ISSUE TITLE
[BUG] Using a virtual scroll makes gesture wrong

### ISSUE THREAD

**Issue by sneko** [yoannmoinet/nipplejs#114]
**Describe the bug**

Hi @yoannmoinet ,

I'm currently using Ionic and they have a component named `ion-content` that acts like a "iframe" to handle user native clicks and scroll.

The main issue I have with Nipple.js is that your library remembers the joystick position according to the body (I guess).

So when I scroll into my `ion-content`, if I try to use the joystick the movement is really slow since I'm really far from the appropriate area. To make it working I need to click first on the joystick (where its UI is), and move my mouse up to the "absolute area" where the joystick has been initialized with the initial virtual scroll.

I guess I could try to modify Nipple properties each time my virtual scroll is triggered, but it would be really consuming. Otherwise modify them just when the event `start` is triggered from the joystick... hmmm...

Is there any way the plugin looks for its current position on the webview? And not thinking about the one at initialization?

I hope it was clear ^^

Thank you,

**Additional context**
- All devices, using Ionic component as virtual scroll (`ion-content`)

**Comment by sneko** [comment]
I succeeded in making it working.

For anyone in the same case, I override the position property of Nipple at the beginning of a touch to be sure the position is right when calculating the moves:
```
      this.joystick.on('start', (event: any, nipple: any) => {
        nipple.position.y = nipple.el.getBoundingClientRect().y;
      });
```

I don't know what could be a proper solution? Maybe give the user the opportunity to override the `getScroll()` located in utils?

I hope it helps :)

**Comment by yoannmoinet** [comment]
I can add a check at the beginning of the `start` event, see if the joystick still has the correct position saved.
Your solution isn't bad, I think I'll add something similar into the lib.
Thank you for the detailed report!

**Comment by yoannmoinet** [comment]
Hm... in fact, it's really specific to how ionic is handling events.

Which is a very specific case, I can't find a real global solution for this.
I think that your workaround is enough for your particular case.

I'll close this issue for now, if it becomes a broader issue, I'll try to have a proper fix.
