### ISSUE TITLE
Not able to move properly inside nested div

### ISSUE THREAD

**Issue by sunildarji811** [yoannmoinet/nipplejs#116]
**Describe the bug**
If I place joystick inside nested container, then it's movement is weird.
I need to drag too much left or top to achieve left or top movement.

**To Reproduce**
1. Go to [https://codepen.io/sunildarji811/pen/ZgBevj]
2. See Static Blue joystick inside second div beside image.
3. try to move it around
4. See result

**Expected behavior**
It should move according to parent div

**Screenshots, Codepen or JSFiddle**
https://codepen.io/sunildarji811/pen/ZgBevj

**Comment by yoannmoinet** [comment]
I tried your example outside of codepen (without all the iframe bootstrap) and I don't see any problem.
If you're able to give me a basic html template to reproduce this bug, I'll reopen the issue.

**Comment by igabesz** [comment]
@yoannmoinet Scroll down in the codepen demo. It works well if everything is at its original position, however, if you scroll a bit down on the page then the center of the scroll detection won't move with the page, but the circles will. 

![image](https://user-images.githubusercontent.com/3373181/68310123-c4d82d80-00af-11ea-9c25-1f884fddc50f.png)

**Comment by igabesz** [comment]
Update: a page resize solves the joystick positioning, the center will be the proper center. Another scroll breaks it again.

**Comment by igabesz** [comment]
Another way to reproduce: it's the demo on the home page. If you add these CSS properties then it breaks the positioning.
![image](https://user-images.githubusercontent.com/3373181/68311276-9bb89c80-00b1-11ea-97d5-b2b5218083de.png)

**Comment by jeryini** [comment]
Hello @igabesz!

I managed to come across the same bug on the WebApp I'm working on. I also noticed that any kind of page resize fixes it. Did you maybe found a temporary fix?

**Comment by jeryini** [comment]
Actually this solution worked for me https://github.com/yoannmoinet/nipplejs/issues/39#issuecomment-401884728
