### ISSUE TITLE
[FEAT] Getting X & Y values in relation to center of joystick instead of (left,right,up,down)

### ISSUE THREAD

**Issue by pazooki** [yoannmoinet/nipplejs#117]
I want to get the numerical value of X and Y in relation to the center of joystick circle. it's gotta be available in your lib just haven't figured how to get it out of it yet..

**Comment by yoannmoinet** [comment]
I'm not sure what you need.

Would it be something like the following?
- `left` is `{x: -1, y: 0}`
- `right` is `{x: 1, y: 0}`
- `top` is `{x: 0, y: 1}`
- `bottom` is `{x: 0, y: -1}`

If so, you can fairly easily do it yourself from the events.

In any case, you should be able to calculate any values you need from what you have in various events and properties. It is straightforward.

For instance, for [every joystick](https://github.com/yoannmoinet/nipplejs#nipple-instance-joystick) you can access the `position` of the center, and the `frontPosition` for the joystick circle. From there, it's trivial to get the coordinates.
