### ISSUE TITLE
[Looking for help] Error on ANGULAR / IONIC 4

### ISSUE THREAD

**Issue by chugoh** [yoannmoinet/nipplejs#136]
Hi I was trying to follow your example on using nipple on ANGULAR / IONIC 4

- ERROR in src/app/tab1/tab1.page.ts(5,8): error TS1192: Module '"/Users/hammerchu/node_modules/nipplejs/types/index"' has no default export.
I tried to do import * as nipplejs from 'nipples' but its gave me some other errors

- ERROR in src/app/tab1/tab1.page.ts(67,14): error TS2339: Property 'on' does not exist on type 'JoystickOutputData'.
src/app/tab1/tab1.page.ts(81,10): error TS2339: Property 'on' does not exist on type 'void'.

I am new to angular and Help would be appreciated

**Comment by yoannmoinet** [comment]
You should look for help on stackoverflow.
I don't think this is an issue with the library.
