### ISSUE TITLE
[FEAT] Pre build of nipplejs ?

### ISSUE THREAD

**Issue by darkworks** [yoannmoinet/nipplejs#138]
**Is your feature request related to a problem? Please describe.**

ya am not able to find build min js file of nipplejs , i downloaded v8.0 from release section but its strange no build file in it 

**Describe the solution you'd like**
please add dist folder where builds are stored so that everyone can get builds directly instead of going through long process of compiling on local machine by install webpacks and tons of dependencies

**Comment by yoannmoinet** [comment]
This is not a feature request.
Build files are already in there thanks to [this](https://github.com/yoannmoinet/nipplejs/blob/master/package.json#L15) and [this](https://github.com/yoannmoinet/nipplejs/blob/master/package.json#L31).
