### ISSUE TITLE
Add a more interactive demo

### ISSUE THREAD

**Issue by yoannmoinet** [yoannmoinet/nipplejs#15]
A little and basic spaceship game.
Dual joystick for touch interfaces (shoot and move).
Solo joystick for mouse interfaces (shoot). Move will be done with WASD.

**Comment by devoxel** [comment]
Are you working on this? I can take a stab at it later, it'd be fun :+1:

**Comment by yoannmoinet** [comment]
I've not yet started to work on it.
Your help is more than welcome.

You can make it in the same form as the other [one](https://github.com/yoannmoinet/nipplejs/blob/master/test/index.html), it's copy pasted on Codepen.

Once in Codepen (if you go this route), you'll have to import : 
- this [js](//yoannmoinet.github.io/nipplejs/javascripts/nipplejs.js) 
- this [css](//yoannmoinet.github.io/nipplejs/stylesheets/styles.css) 
- this [css](//yoannmoinet.github.io/nipplejs/stylesheets/github-light.css)

So we'll be able to visually integrate your demo alongside the others.

Do not hesitate to ping me here if you need any help.

Thanks again.

**Comment by clark-stevenson** [comment]
@yoannmoinet this project is awesome! Exactly what I was looking for and great docs. Keep up the great work.

**Comment by yoannmoinet** [comment]
thanks @clark-stevenson :sweat_smile:. 
If you encounter anything wrong or need to do something more with it, do not hesitate.
