### ISSUE TITLE
[FEAT] Add build file to release section 

### ISSUE THREAD

**Issue by darkworks** [yoannmoinet/nipplejs#150]
Please add build file of nipple js to release section or even to source code add dist folder where there is clean build file like : https://yoannmoi.net/nipplejs/javascripts/nipplejs.js  

however this one : https://yoannmoi.net/nipplejs/javascripts/nipplejs.js   seems to old version missing the recent features

**Comment by yoannmoinet** [comment]
Why?

If you install it with a package manager, it gets built.
If you clone it, you can build it yourself.

This is more hassle for nothing.

**Comment by yoannmoinet** [comment]
https://cdnjs.com/libraries/nipplejs

**Comment by yoannmoinet** [comment]
Here's a PR that should fix the auto-update of cdnjs.
https://github.com/cdnjs/packages/pull/447
