### ISSUE TITLE
[BUG] Nipple position offset based on page layout

### ISSUE THREAD

**Issue by Niksac** [yoannmoinet/nipplejs#155]
**Problem**
Depending on the page structure, the joystick has an offset.

**Codepen**
https://codepen.io/niksac/pen/jOMGQbp
The nipple seems to be offset by the height of the ".someBox"element.

**Affected browsers**
I tested desktop chrome and firefox as well as mobile safari and chrome.

**Additional information**
Using `dynamicPage` will lead to a correctly positioned inner circle.

**Comment by yoannmoinet** [comment]
As stated in the documentation, your container div MUST have a `position` value.
If you add `position: relative` to your `.controllerArea` it's fixed.
