### ISSUE TITLE
Static/semi mode on touch devices creates new nipples or are not dragable

### ISSUE THREAD

**Issue by andersHj** [yoannmoinet/nipplejs#16]
Very cool library, but have some issues on touch devices in static and semi mode

![image1](https://cloud.githubusercontent.com/assets/2843210/10877463/b8041e12-8146-11e5-81e3-64b14b673053.PNG)
On Ipad Air 2, new instances will be created on each touch also in static and semi mode.

On Sony Z2 Tab, most of the time it will not create a new instance, but often the existing instance is not working/dragable (this could be reproduced in chrome developer console by using touch device mode).

**Comment by yoannmoinet** [comment]
Thanks a lot for this.
I'll look into it soon enough.

**Comment by blq** [comment]
Also noticed this.
Seems like the identifier id collides, resulting in multiple instances of "nipple_0" etc causing great DOM confusion.

**Comment by yoannmoinet** [comment]
This should have been fixed in 0.5.4
Can you confirm it?

**Comment by blq** [comment]
No. When I create two static nipples they both get id=0. My case is a simple gamepad style setup. Two simultaneous touches and zombie clones occur.
Line #639 "mode == 'static'" seems to always pass identifier as 0?

**Comment by yoannmoinet** [comment]
Indeed, there is still a nasty bug... once again with multitouch :disappointed:

It looks like it's because of listening / stop listening to events that is somehow un-sync with the mode in use.

Working on it.

**Comment by yoannmoinet** [comment]
0.5.6 should be better with multi-touch.

**Comment by blq** [comment]
Slightly better, no clones appear. But still, the id is duplicated to 0. When touching both one locks up and freezes. I believe this is a bug in the "static" mode? 

As said, isn't a good use-case a gamepad setup? Two side-by-side containers with one static-mode nipple-joystick in each.

**Comment by yoannmoinet** [comment]
Can you show me some code sample so I can reproduce your setup?

**Comment by blq** [comment]
```javascript
var joystickL = nipplejs.create({
    zone: document.getElementById('left-pad'),
    mode: 'static',
    position: { left: '20%', top: '50%' },
    color: 'green',
    size: 200
});

var joystickR = nipplejs.create({
    zone: document.getElementById('right-pad'),
    mode: 'static',
    position: { left: '80%', top: '50%' },
    color: 'red',
    size: 200
});
```

**Comment by yoannmoinet** [comment]
Thanks, I'm looking into this... for sure there is a problem with the lib.
In theory it should have worked.
But it obviously doesn't. I think I have to refactor some stuff.
I'll keep this thread updated.

**Comment by blq** [comment]
Great, thanks!

**Comment by andersHj** [comment]
Thank you for fast fix! 
It now works for my use case on Ipad.
Would be great if it worked with several instances as well.

**Comment by yoannmoinet** [comment]
Please note that there is an opened issue for the multi-instance problem #20.
