### ISSUE TITLE
IIssue with IE 11

### ISSUE THREAD

**Issue by Chruse** [yoannmoinet/nipplejs#17]
Hello!

I have the following issue. We have deployed the  NipplesJS to the following software. Please see link: http://ec2-54-78-224-212.eu-west-1.compute.amazonaws.com/et/pano/show/1441792/separate  On the right bottom corner there is deployed the nipplesJS. 

The issue is that in IE11 there is no the so called Joystick ball (it doesn't show up) The Firefox and chrome are displaying joystick ball correctly. No problems with FF and Chrome. 

If you debugg it you will see error Object doesn't support property or method 'contains'. You can debugg it yourself.

Please help, any suggestions what we have to do to make joystick ball to show up in IE 11.

Thanks in advance,

Christo

**Comment by Chruse** [comment]
On additional comment. If you will click on link , please disable flash. The issue is in HTML5.

**Comment by yoannmoinet** [comment]
Thanks for reporting.

It seems that I'm using `document.contains` to detect if you've added the correct element to the dom.

I should have used `document.body.contains` because IE11 doesn't seem to shortcut it the same way as Chrome and FF.

Thanks for this, I'll fix it this week end.

If you need to fix it right now, I guess you could add something like `document.contains = document.body.contains` when you're in IE11.
This will make the shortcut manually, while I'm fixing it.

**Comment by yoannmoinet** [comment]
Please also note bug #16 with the `static` configuration.

**Comment by yoannmoinet** [comment]
This should have been fixed.
Can you confirm it?

**Comment by Chruse** [comment]
Hello Yaonn,

 

Thanks, issue solved.

 

 

One additional question.

 

If you will look at this link http://ec2-54-78-224-212.eu-west-1.compute.amazonaws.com/et/pano/show/1441792/separate (in case of IE)  and use for the navigation virtual joystick (ball). Is it possible somewhere to change settings that the image movement from right > left or Left> right  etc would be smoother. Currently it is  moving like step by step. The image hangs and moves forward and after that hangs again  and moves forward.

 

 

With flash the image movement is much more smoother.

 

 

Regards,

 

Christo Kuuse

**Comment by yoannmoinet** [comment]
I think I know why you have this behavior.

I you're listening to the `move` event, which is triggered only when your mouse is moving,
you're not constantly moving, this event isn't triggered all the time. 
Only when changed.

In my opinion, you should have a constant movement applied, on which you'd apply a transformation value between : 
- -1 (left) 
- 0 (rest) 
- +1 (right)

And on `move` you'd change this transformation value based on the joystick position.

Though, I understand the need to have a constant triggering when active, 
but it might not give a smoother experience than this.
