### ISSUE TITLE
Not on bower?

### ISSUE THREAD

**Issue by rmp135** [yoannmoinet/nipplejs#24]
Attempting to install using bower returns an error that the package cannot be found, and searching on the [Bower](http://bower.io/search/?q=nipplejs) returns no results.

**Comment by yoannmoinet** [comment]
Oh... this is definitely not normal.
I'll look into this.
Thanks for reporting this.

**Comment by yoannmoinet** [comment]
Ok, this should be fixed now.
![image](https://cloud.githubusercontent.com/assets/597828/11630182/3ceafdfa-9cca-11e5-9527-2c2732a54e9b.png)
