### ISSUE TITLE
Suggestion: Reset events on release

### ISSUE THREAD

**Issue by ThumbGen** [yoannmoinet/nipplejs#25]
Just a small suggestion (reproducible via your demo too) for improving usage of "dir" events:
- move joystick up => the dir:up event is triggered
- release
- move joystick up => the dir:up event is NOT triggered (seems u cache the last status)

Would help a lot getting an event each time the direction changes. Basically after release all "events" should be reset to None or something.

Just an idea

Merry Xmas!

**Comment by yoannmoinet** [comment]
I feel like this is a bug.
It _should_ be reseted.
Somehow, sometimes it's triggered (after at least once).

Thanks for the heads up.
Merry Xmas to you to.

**Comment by ThumbGen** [comment]
Thanks for the fix, helps a lot!

PS: Maybe you can update also the "dist" content as many users directly use those files.

**Comment by yoannmoinet** [comment]
Definitely. 
Thanks for the heads up.
