### ISSUE TITLE
v0.6.1 nipple in Collection.prototype.getOrCreate  is undefined

### ISSUE THREAD

**Issue by roelnoten** [yoannmoinet/nipplejs#26]
There is an issue in v0.6.1
The nipple variable in Collection.prototype.getOrCreate (build artifact) is undefined

**Comment by yoannmoinet** [comment]
Thanks for reporting this.

Do you have any repro steps?
I couldn't reproduce, from basic examples, the behavior.

**Comment by roelnoten** [comment]
Well,
i didn't try to reproduce an issue. But when i open the nipplejs.js in
IntelliJ (my editor) it highlights the error:

[image: Inline afbeelding 1]

I could easily fix by added that first line which is now commented.


Thanks for the great library.

I'm using it on an iphone and have troubles that sometimes the nipple would
remain stuck. I was working with a 2-3 month old version. But now that i
upgraded, this is resolved. Thanks!


Happy new year.
Roel

2015-12-31 4:24 GMT+01:00 Yoann Moinet <notifications@github.com>:

**Comment by yoannmoinet** [comment]
Oh I see... The variable is indeed not instantiated.

It must be coming from the latest somewhat big refactor I did.
I'm not using any codeintel (so sad there is none on Atom).

The 0.6.3 will fix that.

**Comment by yoannmoinet** [comment]
40da2124ab93fed9eac3496dc726e36e99efd6b1 should have fix this.
