### ISSUE TITLE
zone "div" not used but parent node used

### ISSUE THREAD

**Issue by pedefe** [yoannmoinet/nipplejs#27]
I have created two "div" in a jqxWindow area.
I need to create two joysticks, one in each "div"
The joysticks are created with position relative to jqxWindow and not relative to "div".
What can be the explaination ?

**Comment by yoannmoinet** [comment]
Hi, thanks for reporting this.
Do you have something to show me your setup please?
Like a codepen, jsfiddle or something else.

**Comment by yoannmoinet** [comment]
Anything @pedefe ?

**Comment by vgabor99** [comment]
Hi,

I have the same problem. I want the joystick zone be relative to a div, but it is offset to the page instead.
https://jsfiddle.net/6q6278xe/6/
(The big bunch of javascript code is jsnipple)

Thanks,
Gabor

**Comment by yoannmoinet** [comment]
Thank you @vgabor99, this is really appreciated.

The containing div has to have a `display` prop.
Either `relative` or `absolute`.
I've updated your [jsfiddle](https://jsfiddle.net/6q6278xe/7/) @vgabor99.

**Comment by vgabor99** [comment]
Thanks @yoannmoinet , working perfectly.

**Comment by yoannmoinet** [comment]
@vgabor99 do you think the library should make the check itself?

@pedefe does that fix your problem?

**Comment by vgabor99** [comment]
Maybe the library should log a warning if the container does not have a position property. This would help beginners like me.

**Comment by yoannmoinet** [comment]
Good call.
I'll also add a warning in the documentation.

**Comment by yoannmoinet** [comment]
added a nota in the readme 59b4ca4835242daa15e35f024a8ed22820ec0fbb
