### ISSUE TITLE
'onresize' should use addEventListener

### ISSUE THREAD

**Issue by blq** [yoannmoinet/nipplejs#29]
I notice that the window onresize listener is attached by setting the property "window.onresize = function() {...}". 
I suggest changing this to use addEventListener instead to avoid risking clash with existing code that also attaches to onresize.

**Comment by yoannmoinet** [comment]
> avoid risking clash with existing code that also attaches to onresize

Never thought of that that way... very good point.

Do you want to PR it? 
You can use the `u.bindEvent(el, type, handler)` helper.

**Comment by blq** [comment]
Nah, feels like such a tiny edit that, unless you insist, I leave to the original author :)

**Comment by yoannmoinet** [comment]
fixed by 14c28f1ef868abc99e63761b208d9eb2a796bb54
