### ISSUE TITLE
Joystick gets stuck

### ISSUE THREAD

**Issue by bfishman** [yoannmoinet/nipplejs#31]
I'm using Nipple.js on two separate transparent elements, overlaid on top of an HTML canvas - a 'left' and 'right' element. This allows me to use two joysticks for a 'twin stick shooter' style game.

I'm having a lot of trouble determining _when_ this actually happens, but it is happening quite frequently:  the right joystick "locks up", frozen at the max extent of its bounds, and cannot be released without a page refresh.  The left joystick never seems to lock up (it is defined first in my code).

Part of the difficulty in debugging this is that it only happens when using a phone to visit the website, and as such my debugging tools (namely access to the browser console) are practically non-existent.  In the browser, I cannot reproduce the bug.

It also seems to happen only when there are 2 joysticks active at once. If only 1 joystick is used (despite both having been instantiated), the problem doesn't seem to surface.

Any ideas? I'm digging through your code to see if I can spot where this bug might come from, but figured I would bring it up in case you are able to spot the issue more easily.

Might not be relevant, but here's my usage:

```
function initializeMovementJoystick(){
    movementJoystick = NippleJS.create({zone: leftDiv});
    var currentOctant = null;
    var octants = new Array(8);
    octants[0] = function(state){InputHandler.setInputState("strafeRight", state);};
    octants[1] = function(state){InputHandler.setInputState("strafeRight", state);InputHandler.setInputState("forward", state);};
    octants[2] = function(state){InputHandler.setInputState("forward", state);};
    octants[3] = function(state){InputHandler.setInputState("strafeLeft", state);InputHandler.setInputState("forward", state);};
    octants[4] = function(state){InputHandler.setInputState("strafeLeft", state);};
    octants[5] = function(state){InputHandler.setInputState("strafeLeft", state);InputHandler.setInputState("backward", state);};
    octants[6] = function(state){InputHandler.setInputState("backward", state);};
    octants[7] = function(state){InputHandler.setInputState("strafeRight", state);InputHandler.setInputState("backward", state);};

    movementJoystick.on('end move', function(event, data){
        if (event.type === 'move'){
            if(data.distance < 15){
                if (currentOctant !== null){
                    //un-fire current
                    octants[currentOctant](false);
                    currentOctant = null;
                }
            } else {
                let angle = data.angle.degree;
                let octant =  Math.floor(((angle + 22.5) % 360) / 45.0);

                if(octant !== currentOctant){
                    if(currentOctant !== null){
                        //changed from one to another, un-fire last
                        octants[currentOctant](false);
                    }
                    //fire current
                    octants[octant](true);
                    currentOctant = octant;
                }
            }
        } else if (event.type === 'end'){
            if (currentOctant !== null){
                octants[currentOctant](false);
                currentOctant = null;
            }
        }
        //console.log(event);
        //console.log(data);
    });
}

function initializeRotationJoystick(){
    rotationJoystick = NippleJS.create({zone: rightDiv});
    var currentOctant = null;
    var octants = new Array(8);
    octants[0] = function(state){InputHandler.setInputState("turnRight", state);};
    octants[1] = function(state){InputHandler.setInputState("turnRight", state);InputHandler.setInputState("boost", state);};
    octants[2] = function(state){InputHandler.setInputState("boost", state);};
    octants[3] = function(state){InputHandler.setInputState("turnLeft", state);InputHandler.setInputState("boost", state);};
    octants[4] = function(state){InputHandler.setInputState("turnLeft", state);};
    octants[5] = function(state){InputHandler.setInputState("turnLeft", state);InputHandler.setInputState("shoot", state);};
    octants[6] = function(state){InputHandler.setInputState("shoot", state);};
    octants[7] = function(state){InputHandler.setInputState("turnRight", state);InputHandler.setInputState("shoot", state);};

    rotationJoystick.on('end move', function(event, data){
        if (event.type === 'move'){
            if (useRelativeOrientation){
                InputHandler.setInputState("targetAngle", data.angle.degree);
            } else if(data.distance < 15){
                if (currentOctant !== null){
                    //un-fire current
                    octants[currentOctant](false);
                    currentOctant = null;
                }
            } else {
                let angle = data.angle.degree;
                let octant =  Math.floor(((angle + 22.5) % 360) / 45.0);

                if(octant !== currentOctant){
                    if(currentOctant !== null){
                        //changed from one to another, un-fire last
                        octants[currentOctant](false);
                    }
                    //fire current
                    octants[octant](true);
                    currentOctant = octant;
                }
            }
        } else if (event.type === 'end'){
            if (currentOctant !== null){
                octants[currentOctant](false);
                currentOctant = null;
            }
        }
        //console.log(event);
        //console.log(data);

    });
}
```

**Comment by yoannmoinet** [comment]
Thanks for reporting it, I'll look into this.

**Comment by bfishman** [comment]
I will message you privately.

**Comment by yoannmoinet** [comment]
Ok, so after testing it, I might have found a way to reproduce it.

I was able to reproduce the phenomenon by activating the right joystick, while playing with it, rotate the phone.
Then release your finger, and the joystick will stay activated.
After that, if you active the left joystick, both will tracked the same finger.
Release, and only the right one will de-activate, and the right one will stay stuck for ever.

Is it the behavior you were having?

It could be related to #30. This looks like an edge case, but definitely a bug.
I'll have to think what the joystick should do in this situation.
Kind of a tough one...

**Comment by bfishman** [comment]
It is not the same behavior, but I have seen that happen as well. Perhaps
they are related and one solution will fix both.

I will try to come up with a better repro..

**Comment by mlknz** [comment]
Having same issue. Reproduced by creating one static and one dynamic nipples on different dom elements. 
`addedNipples = 0;`
`removedNipples = 0;`
`lookNippleManager.on('added', (evt, nipple) => {`
`    addedNipples++;`
` }).on('removed', (e, nipple) => {`
`    removedNipples++;`
`  });`

When bug happens having `addedNipples === removedNipples + 1`. Spamming touches helps in reproducing, but is not necessary.
Platforms: desktop Chrome on Ubuntu 14.04. Mobile Safari on multiple ios devices.

**Comment by yoannmoinet** [comment]
Thx @mlknz to add more details to this.
I'm still having a hard time pinpointing this (ANNOYING) bug.

**Comment by mlknz** [comment]
@yoannmoinet couldn't reproduce bug with dataOnly param set to true. Could it be dom manipulation related issue?

**Comment by yoannmoinet** [comment]
@mlknz it could be indeed.

I don't have much time on this right now, so feel free to investigate.
I'm fixing the issue you have with the dev workflow and I'm almost there.

**Comment by mlknz** [comment]
Found easy way to reproduce bug:
start a new touch on old joystick container before it gets removed from `options.zone`. This way `Collection.processOnEnd` is not called after releasing touch.

Basically slow double tap works.

**Comment by colmakers-antonio** [comment]
hi, I have fixed a similar issue by adding this line "|| self.binded" in this function in this file dist/nipplejs.js 

`Manager.prototype.unbindDocument = function (force) {
    var self = this;
    // If there are no touch left
    // unbind the document.
    if (!Object.keys(self.ids).length || force === true || self.binded) {
        self.unbindEvt(document, 'move')
            .unbindEvt(document, 'end');
        self.binded = false;
    }
};`

**Comment by kevzettler** [comment]
I am seeing this happen with `nipplejs@0.6.8` 

I think this only happens `dataOnly: false` and the DOM elements are rendered. 

There are now error warnings thrown.  The behior that happens is the joy stick UI DOM elements just freeze or lockup, The joystic UI remains visible on screen and cannot be manipulated.

**Comment by kevzettler** [comment]
great find @robertlong

**Comment by robertlong** [comment]
I've done some more research today. It looks like the second `touchend` is not fired on mobile Safari or Mobile Firefox on Android when you do a slow double tap. This causes the second nipple element to get stuck.

**Comment by robertlong** [comment]
I ended up getting stuck on this. It probably has something to do with `event.preventDefault()` or returning false from an event handler, but I couldn't figure out what handler was causing the issue. Most of the occurrences of this issue can be solved by setting `fadeTime: 0` so I'm going to stick with that for now.
