### ISSUE TITLE
Container div offset causes weird hitbox issues

### ISSUE THREAD

**Issue by ablakey** [yoannmoinet/nipplejs#32]
The div that is created by nipplejs to contain the two circle divs has a very odd offset where the top-left corner is the centre. You can see in the screenshot below via. Chrome. You can also see this in the hosted demos by selecting the element in your browser's developer tools.

The problem is twofold:

1. It overlaps with other elements, stealing their clicks.
2. It makes the area that controls the joystick inconsistent.

This bug seems to have been masked by the fact that it isn't evident if you have a large enough area for your joystick to work in.

![njs_hitbox](https://cloud.githubusercontent.com/assets/9021944/16926831/84a10020-4cf8-11e6-9927-27338b3747c5.png)

**Comment by yoannmoinet** [comment]
Thanks for reporting this.
I'll look into it later today.

**Comment by yoannmoinet** [comment]
@ablakey I've pushed a new version 0.6.4

Please, tell me if that fixed your issue.

Thanks.
