### ISSUE TITLE
joystick get stuck on iphone

### ISSUE THREAD

**Issue by luckylooke** [yoannmoinet/nipplejs#33]
There is method prepareCollections() on Manager.prototype, but when it is called it doesnt work. You can test it via safari remote debug in console.

```
a = [];
a.test = function(){console.log('test')};
a.test(); // returns undefined for first time
a.test(); // returns 'test' every other attempt
```

I think that is the reason why it get stuck. You can test it on your DEMO (dynamic) as well, just open it on iphone and quickly repeat different touches, best with two fingers. Same for chrome or safari. It seems to me like a bug in safari, but you should fix it anyway, because there is lot of users with iphones.

![screenshot](https://cloud.githubusercontent.com/assets/3660030/17021591/3e6efe7e-4f49-11e6-8173-6ee768a6a883.jpg)

**Comment by yoannmoinet** [comment]
Thanks for reporting this, I'll look into it.

**Comment by ELundby45** [comment]
I've noticed that this problem occurs significantly less if I set the fadeTime to 0.

**Comment by kevzettler** [comment]
I've also encountered this problem

**Comment by adriancabouli** [comment]
touchcancel event it fix the problem!, 

$(document).on('touchcancel', function(event) {
   REMOVE_AND_CREATE_JOYSTIC()	// or whatever... 
});
