### ISSUE TITLE
Broken dataOnly parameter.

### ISSUE THREAD

**Issue by mlknz** [yoannmoinet/nipplejs#35]
Created dynamic nipple with `dataOnly: true` parameter.
On touch having this in Chrome / Ubuntu:
`nipplejs.js:336 Uncaught TypeError: Cannot read property 'stylize' of undefined`

In code:
`this.buildEl().stylize();`

At the very beggining of `buildEl` function:
`if (this.options.dataOnly) {
        return;
    }`

**Comment by yoannmoinet** [comment]
Nice one, will fix soon.
I'm not using `dataOnly: true` very often 😉

**Comment by yoannmoinet** [comment]
Actually, 
if you want to submit your PR to have it sooner, 
it would simply need to `return this;` in both `buildEl` and `stylize` to keep the chainability.

As you wish, I'll do it this evening if you don't.

**Comment by yoannmoinet** [comment]
I've merged your PR, thank you !

I'll push a new build this evening.

**Comment by mlknz** [comment]
Thanks!
