### ISSUE TITLE
Dev build workflow.

### ISSUE THREAD

**Issue by mlknz** [yoannmoinet/nipplejs#37]
Npm install failed at `phantomjs@2.0.0-alpha1`.

Npm run build fails (cannot find module core-util-is in format task).

Also i suggest having dev branch ahead of master (had nowhere to merge but master which is not good).

Node v6.2.0, npm v3.7.3, ubuntu 14.04.

**Comment by yoannmoinet** [comment]
what platform are you on?

**Comment by yoannmoinet** [comment]
For the branch, I don't use dev branches anymore.
Only hotfixes and feature branches.

**Comment by yoannmoinet** [comment]
Ok, I'll try to update all the dependencies we have.
It might fix the cross-platform issue.

**Comment by yoannmoinet** [comment]
I've updated all the dependencies.
Can you tell me if it helps?

**Comment by mlknz** [comment]
All tasks work fine now!
Tests: 2 passed, 7 failed.

Details for the 7 failed tests:

```
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertExists: Active zone is found
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertExists: Nipple 0 from collection 0 is found
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertExists: Nipple 0 from collection 0 is found
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertVisible: Semi zone should be visible
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertExists: Nipple 0 from collection 1 is found
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertVisible: Static zone should be visible
In ./test/nipplejs.casper.js
  NippleJS test page loads correctly
    assertExists: Nipple 0 from collection 2 is found
```
