### ISSUE TITLE
Simultaneous touch events

### ISSUE THREAD

**Issue by ablakey** [yoannmoinet/nipplejs#38]
Has anyone experimented with a way to emulate the ability to simultaneously use the joystick and touch other elements like buttons, dragging a map around, etc. ?

I have luck getting multiple joysticks to work together, but have not had any luck getting a joystick and a button to work together.

**Comment by yoannmoinet** [comment]
@ablakey can you share a bit more on your setup please?
Like a jsfiddle or a codepen would help understand your issue.
Thanks.

**Comment by ablakey** [comment]
Sure. Will have to wait until I get to work on Tuesday as I have no multitouch devices at home with me.

**Comment by mlknz** [comment]
I've got in similar issue. Basically I have a button in top 10% and joystick zone in bottom 90%. In chrome mobile emulator everything works fine, but on real device button doesn't work (as soon as at least one joystick touch was started). You could look at it [here](https://mlknz.github.io/Dungeonizer.js/) (press "Take a walk" from mobile device and then try to press "Exit" in top left corner). [Link to related code](https://github.com/mlknz/Dungeonizer.js/blob/master/src/scripts/dungeonVisualizer/controls.js) (look at enableWalker / disableWalker / _initTouchJoystick methods).

**Comment by yoannmoinet** [comment]
Thanks @mlknz for the testable example. 
I'll have a look as soon as possible.

**Comment by boxabrain** [comment]
Similar problem here, in static mode all other UI elements event were prevented.

Partially solved with a quick (but dirty) fix in nipplejs.js, applying preventDefault() only if event target is a joystick:

`u.prepareEvent = function (evt) {
	if (evt.target.className == 'front' || evt.target.className == 'back') evt.preventDefault();
    return evt.type.match(/^touch/) ? evt.changedTouches : evt;
};`

I didn't tested how it affects on other modes but it worked for me.
It's not a definitive solution to the problem... but it may help :)

**Comment by jaean123** [comment]
Thanks @boxabrain 
That line of code fixed the issue!

**Comment by adriancabouli** [comment]
touchcancel event it fix the problem!, 

$(document).on('touchcancel', function(event) {
   REMOVE_AND_CREATE_JOYSTIC()	// or whatever... 
});

**Comment by ramasilveyra** [comment]
This error is still present on the latest version while using multiple static nipples. The change shared by @boxabrain fixes the issue, thanks!

**Comment by yoannmoinet** [comment]
@ramasilveyra can you share more details on how this is still an issue?
How can I reproduce?

Thanks.

**Comment by manmohanbishnoi** [comment]
I can notice this bug on iOS (Chrome and Firefox)
But Android browsers work well without any issues.
