### ISSUE TITLE
Events stop working after first end

### ISSUE THREAD

**Issue by vrracing** [yoannmoinet/nipplejs#40]
Hi.  Using a static nipple everything works great on first use.  On second use, only the start is captured; move and end are ignored.

Fiddle here...

https://jsfiddle.net/ykotkzow/18/

Thanks!

**Comment by yoannmoinet** [comment]
Oh... looks like the lib is missing some triggers.
Specifically the ones with the id of the joystick.

I've updated the fiddle to have a temporary solution: https://jsfiddle.net/ykotkzow/19/
By listening to general events.

This is a bug though.

**Comment by vrracing** [comment]
That works.  Thanks @yoannmoinet

**Comment by yoannmoinet** [comment]
This has been fixed in 0.6.7
