### ISSUE TITLE
Lock joystick to move only on a certain axis

### ISSUE THREAD

**Issue by j-cali** [yoannmoinet/nipplejs#42]
Is there a way to restrict joystick movement only a certain axis?
For example, locking it on the y-axis for zoom in/out functionality. Thanks.

**Comment by yoannmoinet** [comment]
That would be a great new feature.
I'll label it as it.

Thanks!

**Comment by ELundby45** [comment]
I anticipate taking a shot at implementing this in the coming weeks and will definitely submit a PR if I get it working. If you've already thought about this, or have any ideas on implementation, I would love to hear your thoughts.

**Comment by falkoschindler** [comment]
Sounds great!

I somehow enforced the nipple to stay centered via CSS:

```
.nipple {
    left: 50% !important;
}
.nipple .front {
    width: 50px !important;
    height: 50px !important;
    margin-left: -25px !important;
    margin-top: -25px !important;
    left: 0 !important;
}
```

But a Javascript-based solution on your side would be much better, I guess.

**Comment by yoannmoinet** [comment]
Hi, thank you for your interest in this.

What I was seeing is a new setting passed at the `nipplejs.create(options)` phase.

Something like `lockX` and `lockY` as booleans.
Then it can be enforced [here in the code.](https://github.com/yoannmoinet/nipplejs/blob/master/src/nipple.js#L287)

Feel free to take a shot at this, I will be more than happy to review your contribution.
I'm currently a bit out of bandwidth for this.

Cheers!

**Comment by hippiewho** [comment]
Hi,
I've taken a shot at it, although i'm not completely sure if I enforced all events to reflect that an axis is locked.

**Comment by yoannmoinet** [comment]
Thank you @hippiewho, the feature has been added to `0.7.0`!
