### ISSUE TITLE
Help with initialising joystick

### ISSUE THREAD

**Issue by d3Niro** [yoannmoinet/nipplejs#43]
Hello, I am relatively new to node.js. This package is exactly what I need for a little hobby project of mine, but I am unable to initialize the joystick in a web app. What .html, .js, and .css code is needed for the bare minimum joystick on a blank web app? I can figure things out from there, would really appreciate any help in getting started.

**Comment by yoannmoinet** [comment]
Hi,
everything you need is listed in the documentation.
http://yoannmoinet.github.io/nipplejs/#demo
