### ISSUE TITLE
Help to make nipplejs works on React Native

### ISSUE THREAD

**Issue by nvl1109** [yoannmoinet/nipplejs#44]
Hi,

I would like to get nipplejs works on React Native, or alternative package on react native also helpful.
Do you have any plan to support/porting nipplejs to React Native? Or can you give me a quick guide?

Thank you.

**Comment by yoannmoinet** [comment]
Hi,
unfortunately, I don't have much time to implement new stuff.

I wanted to first make everything ES6.
Then we'll see for the React(-Native) part later.

**Comment by PixelsCommander** [comment]
@nvl1109 why not https://facebook.github.io/react-native/docs/webview ?

**Comment by loopmode** [comment]
Hi.

I just released a react wrapper - it was fairly simple and straight-forward.
While I have nothing to do with react-native, I guess there shouldn't be much trouble doing necessary adjustments.

See https://www.npmjs.com/package/react-nipple
See https://github.com/loopmode/react-nipple/blob/master/packages/react-nipple/src/ReactNipple.js

**Comment by yoannmoinet** [comment]
There is a `dataOnly` mode with the library, I don't remember completely, but in theory it shouldn't go through the dom. 

Maybe you could leverage it somehow. 

Let me know how it goes.

**Comment by wrinkledcheese** [comment]
This would be awesome!  There's NOTHING that works for me™ in the controller input area.  All I could find were two libs about a year old that depended on es2015 babelrc presets and after 15 minutes of trying the wife and kids required attention.  I just want a joystick for the Arduino robot my  sons and I are building.  I was hoping to cobble together a Bluetooth remote for android in a weekend.  Proving to be difficult.

The results would end up on github as 'lazer robot st1000 remote' which is what my sons want to call it.

I will check out the dataOnly mode and see if I can get er to chooch.

**Comment by jim-at-jibba** [comment]
I have written a React Native component that uses this package. 
@wrinkledcheese let me know if there are any other features you want I will look to add them. 

It can be found here: https://www.npmjs.com/package/react-native-game-pad

**Comment by yoannmoinet** [comment]
@jim-at-jibba proposed a solution.

I might get a shot at this later. Offer a bit more deeply integrated solution for React/React-Native.
