### ISSUE TITLE
Make joystick visible by default in semi mode

### ISSUE THREAD

**Issue by praveenaj** [yoannmoinet/nipplejs#47]
I want to show joystick once plugin is initialized, not on click. I tried `static` mode but in that I want just the joystick to move and keep outer circle stationary as it is now. I'd like to have your recommendations. Thanks

**Comment by yoannmoinet** [comment]
I'm not sure I understand, this is what static does.
Have you tried the examples in static mode ? http://yoannmoinet.github.io/nipplejs/#demo

**Comment by praveenaj** [comment]
@yoannmoinet Yes, in other words `static` mode with a moving joystick.

**Comment by yoannmoinet** [comment]
So, I don't have much free time at the moment. So if you really need this, please feel free to take a shot at it and submit a PR, I'll be more than happy to review it.

**Comment by praveenaj** [comment]
Sorry for the confusion. It turns out I have missed `position` property when I tested `static` mode. This made the joystick not moveable. All good when I set 50%-50% for left and top. 
Thanks for creating this awesome library.
