### ISSUE TITLE
Nipple hijacks events on iPad?

### ISSUE THREAD

**Issue by andersHj** [yoannmoinet/nipplejs#48]
After updating to version 0.6.7 I have had some problems on iPad:
The problem is that after I first touch the joystick/nipple other events on my page will not work anymore.

To **reproduce** open the demo page:
https://yoannmoinet.github.io/nipplejs/
on an iPad and click the **static** tab, and **touch** the nipple.
Then try to change to one of the other tabs (dynamic or semi)

Edit: it is also a problem in "semi" mode, but then you have to touch it twice before it "breaks"
The problem is not there in v0.6.6

**Comment by yoannmoinet** [comment]
Hm, thank you for reporting this.
I'll have a look as soon as possible.

**Comment by GuskiS** [comment]
Just noticed this on Iphone SE, works fine in v0.6.6.

**Comment by yoannmoinet** [comment]
duplicate of #38
