### ISSUE TITLE
Stop Joystick swapping back

### ISSUE THREAD

**Issue by dinukalakshan** [yoannmoinet/nipplejs#49]
Hi yoannmoinet, Love your work! 
Is there a way to station the joystick knob where the user moved it to without it swapping back to its original position? 
I want to achive this -

![nipplejs](https://user-images.githubusercontent.com/22944281/27140349-ebd417ec-5142-11e7-8e51-16d212b71a94.gif)

Thanks!

**Comment by yoannmoinet** [comment]
This could be possible, using a static joystick and adding a new option in the code.

Then, put this [statement](https://github.com/yoannmoinet/nipplejs/blob/73bcda952d01882566a72dd52ec3678548eefe51/src/nipple.js#L233) behind the condition of this option.

That would block the movement and keep the joystick in its latest position.

I don't have much time, feel free to submit a pull request for this.
Or I'll try to add it sometime later.

**Comment by MalithHatananchchige** [comment]
@yoannmoinet Thanks, alot, works like a charm. I have sent you a pull request. 
https://github.com/yoannmoinet/nipplejs/pull/50

**Comment by yoannmoinet** [comment]
Wow! thank you @MalithHatananchchige for the fast PR !! 🙌 
I'll have a look later this week I sware!

**Comment by milankragujevic** [comment]
Updates?

**Comment by yoannmoinet** [comment]
Waiting for @MalithHatananchchige PR to be updated.

**Comment by UniquePassive** [comment]
I was looking for this feature too, so I added it and made a PR: https://github.com/yoannmoinet/nipplejs/pull/59, could be useful if @MalithHatananchchige hasn't got a fix for his PR close at hand.

**Comment by yoannmoinet** [comment]
Has been closed with #59
