### ISSUE TITLE
Calling `stylize` after init

### ISSUE THREAD

**Issue by GuskiS** [yoannmoinet/nipplejs#52]
Is it possible to call `stylize` after I have inited static nipple? I would like it to recalculate the size and position if I change the options.

**Comment by yoannmoinet** [comment]
Try it. I don't know.

**Comment by yoannmoinet** [comment]
From what I read in the code [here](https://github.com/yoannmoinet/nipplejs/blob/master/src/nipple.js#L89) it might be possible.

**Comment by yoannmoinet** [comment]
Please, next time put a bit more effort in your investigation (actually testing what you're trying to achieve) before opening an issue here.
Thanks.

**Comment by GuskiS** [comment]
I was looking at the code and testing stuff. What I noticed was that https://github.com/yoannmoinet/nipplejs/blob/master/src/nipple.js#L56 returns custom instance of available functions, but `stylize` is not one of them. I was unable to get to that function myself so I was asking here. Sorry for not saying what I have tried.

**Comment by yoannmoinet** [comment]
Oh you're right, `stylize` isn't part of the available api. 

But if you stylize your joysticks via css you won't need it. 
You can find the html of the joystick [in the doc](https://github.com/yoannmoinet/nipplejs/blob/master/README.md#joystickel), so you can target its element via css.

**Comment by yoannmoinet** [comment]
Or, if you need, you could submit a PR that would expose `stylize` in the available api. 

With the associated doc. I'll gladly review it.

**Comment by yoannmoinet** [comment]
If this is still needed, feel free to re-open with a use-case.
