### ISSUE TITLE
Is it possible to get -X/+X and -Y/+Y and/or min/max value going from center?

### ISSUE THREAD

**Issue by miharix** [yoannmoinet/nipplejs#54]
Hi!

How can I get the distance from the nipple to center like a cartesian system ?

I'm trying to implement your nipplejs code in my small project https://github.com/miharix/miharix-wifi-rc/
To do this, I need the X/Y max/min value (optimal would be if I can define the range) so I can calculate the responding ° for the servo move. Or least the X and Y distance from center that contains +/- depending on the direction.

Is this possible in current nipplejs version?

**Comment by yoannmoinet** [comment]
I'm not sure I totally understand what you need.
Maybe you'll find it here https://github.com/yoannmoinet/nipplejs#move, in the documentation.

**Comment by miharix** [comment]
If it's not possible I'll make some approximation from existing data, but I think that this could be useful also for somebody else.

To control RC servo I have to send him value in degree(0-180°) or in PWM(0.5-2.5ms)
I'm using nipple in static mode and dynamic container/circle size, depending on screen resolution.
So if I want to control servo on example nipple's X movement,
 and make it move exact and whole range,
 I need min/max range of the nipple, current nipple distance from center and direction.

So optimal in my case would be, if I could define nipple X range 0-180 and center is 90
Or more universal nipple X min -90, nipple X max +90, center 0

So on nipple move I would like to get the nipple X and Y coordinates, relative to the big circle center(X=0, Y=0) and some min code fixed value of how far the nipple can travel.

**Comment by miharix** [comment]
Leaving here the solution for my small problem:

```
d= document,
e = d.documentElement,
g = d.getElementsByTagName('body')[0],
x = w.innerWidth || e.clientWidth || g.clientWidth,

nip_size=x/4;
max_rangeX=180;
min_rangeX=0;
max_rangeY=180;
min_rangeY=0;

var joystickL = nipplejs.create({
            zone: document.getElementById('leftB'),
            mode: 'static',
            position: { left: '50%', top: '50%' },
            color: 'green',
            size: nip_size,
            restOpacity: 1
 });

joystickL.on('move',function (evt, data){
 if(((data.angle.degree<90)&&(data.angle.degree>0))||((data.angle.degree<360)&&(data.angle.degree>270))){
	X=Math.cos(data.angle.radian)*data.distance;
	Y=Math.sin(data.angle.radian)*data.distance;
}
if(((data.angle.degree<180)&&(data.angle.degree>90))||((data.angle.degree<270)&&(data.angle.degree>180))){
	X=-Math.cos(Math.PI-data.angle.radian)*data.distance;
	Y=Math.sin(Math.PI-data.angle.radian)*data.distance;
}
      
Servo1=((X+nip_size/2)*(max_rangeX-min_rangeX)/nip_size+min_rangeX).toFixed(0);
Servo2=((Y+nip_size/2)*(max_rangeY-min_rangeY)/nip_size+min_rangeY).toFixed(0);
});
```
X & Y are in range from -size/2 to size/2 
XY(0,0) is the center
Servo1 uses only X and is between max_rangeX and min_rangeX.

**Comment by yconst** [comment]
How come this feature is missing? It's really elementary stuff...

**Comment by yoannmoinet** [comment]
@yconst I don't know. Maybe with a better attitude it could be implemented by the owner later.

In the meantime, feel free to do it yourself and even submit a PR for it.

Cheers.

**Comment by iodev** [comment]
see if what I added in commit 853aaf3a4080bbffe0df52d9682517355a50c895 fixes it for you

**Comment by DominicChm** [comment]
I also needed this functionality, so I came up with a monkey patch to get it done. Since this is the first thing that shows up in Google, I'll put it here.
```javascript
var manager = nipplejs.create({
	zone: document.getElementById('container');
});


//Copy below to emit patched movement events
manager.on('start', function (evt, nipple) {
    const {x, y} = nipple.position;
    nipple.on('move', function (evt, nipple) {
        nipple.root = {x, y}

        nipple.movement = {
            x: nipple.position.x - nipple.root.x,
            y: nipple.root.y - nipple.position.y
        }

        nipple.normalized = {
            x: 2 * (nipple.position.x - nipple.root.x) / nipple.instance.options.size,
            y: 2 * (nipple.root.y - nipple.position.y) / nipple.instance.options.size
        }

        nipple.instance.trigger("movement", nipple); //Emit patched event

    }).on("end", function (evt, nipple, test) { //Fire a movement event when the nipple returns to center
        nipple.root = {x, y}
        nipple.movement = {x: 0, y: 0}
        nipple.normalized = {x: 0, y: 0}

        nipple.trigger("movement", nipple); //Emit patched event
    })
});


//Function to print new fields
function onMovement(event, nipple) {
    console.log(
        nipple.movement,
        nipple.normalized,
        nipple.root
    );
}


//Listen to patched events by using "movement" rather than "move"
const nipple = manager.get(0);
nipple.on("movement", onMovement);


//Doesn't work with manager move events! Seems like it's harder to patch that.
//Use below instead of manager.on("move") to allow the patch to apply to events from all nipples.
manager.on("start", (e, n) => n.on("movement", onMovement));

```

The new event contains a `normalized` field that contains x and y ranges from -1 to 1, which will probably be most useful.

**Comment by funwithtriangles** [comment]
You can use trigonometry to work this out using the angle and distance, which is provided as data:

```javascript
const angle = data.angle.radian
const dist = data.distance
const x = (Math.cos(angle) * dist) / 50
const y = (Math.sin(angle) * dist) / 50
```
