### ISSUE TITLE
Refresh 'center' coordinates for nipple

### ISSUE THREAD

**Issue by dggsax** [yoannmoinet/nipplejs#55]
Hiya. I'm working with nipplejs and have a function that builds nipples from a configuration json file. My web app uses [shapeshift](http://mcpants.github.io/jquery.shapeshift/) to make things draggable. So, essentially all my of modules (including my nipples) get built in a div like this:
![image](https://user-images.githubusercontent.com/13513445/29443675-8f918bc6-83a7-11e7-8e1d-bfb99d7ac7d9.png)
And then the shapeshift function is called to sort everything to look like this:
![image](https://user-images.githubusercontent.com/13513445/29443682-9b9e9f6c-83a7-11e7-95ef-0231637df5ff.png)
However, there's one small issue. Since the nipples first rendered as in the first photo, the createNipple function set the 'center' (I guess x,y position) there, so when shapeshift moves everything around, the nipples still think the 'center' x,y positions are originally where they were created.
I made a fix for this by just creating the container div's for the nipples, calling shapeshift, and then having the nipples be created after the fact so that they work properly (as in the second photo). I was wondering if there was a way to update the x, y position for a certain nipple, or all nipples, whenever the location of their div moves around?

Let me know if you want to see my code or if I need to explain things better. Thanks!

Gonzo

**Comment by dggsax** [comment]
One solution I was thinking of was rebuilding the nipples everytime the page moves as a result of shapeshift. But am having a hard time implementing the .destroy() function, unsure whether I should be calling nipplejs.destroy('#NippleID');. Any tips? @yoannmoinet

**Comment by yoannmoinet** [comment]
Hi,
see if you could do something similar to the built-in `resize` event handler, [here](https://github.com/yoannmoinet/nipplejs/blob/master/src/manager.js#L25).

For the `destroy` function, you can call it either on the [nipple instance](https://github.com/yoannmoinet/nipplejs/blob/master/src/nipple.js#L168) directly, that will destroy the nipple itself, on the [collection](https://github.com/yoannmoinet/nipplejs/blob/master/src/collection.js#L488), it will destroy all nipples linked to this collection (created when called via `manager.create(options)`). Or finally on the [manager](https://github.com/yoannmoinet/nipplejs/blob/master/src/manager.js#L197), and this will destroy all collections, and all nipples.

Keep me posted if you have any issue.
Cheers.

**Comment by dggsax** [comment]
Hello again,

Storing nipple objects in an array and just iterating the .destroy() function did the trick. Thanks for the help!

Daniel
