### ISSUE TITLE
Joystick is not released when moved out of the window only chrome and IE

### ISSUE THREAD

**Issue by sharath1512** [yoannmoinet/nipplejs#57]
For a static joystick, when we drag the joystick outside the position where it exists, the joystick is not released and we have to do an extra click to release it. 

Steps:

1. drag the joystick outside the position where it is created (like into the white space.)
2. Observe that it is not released.

**Comment by yoannmoinet** [comment]
Do you have a setup I can test.

I can't reproduce it in the demo.

http://yoannmoinet.github.io/nipplejs/#demo

**Comment by sharathava** [comment]
Hi,

This can be reproduced in demo. This happens on IE and chrome but not on firefox. This is for the static mode (static tab).

**Comment by yoannmoinet** [comment]
what would be the expected behavior?

**Comment by sharathava** [comment]
I would expect the behaviour should be as it is behaving in the firefox. The joystick should be released.

**Comment by yoannmoinet** [comment]
that would be cool indeed, the issue is Chrome (and probably IE too) won't let you track the mouse move outside the window.
So it can't be the same as Firefox.
I could make it like it would release the joystick as soon as the cursor goes out of the window.

**Comment by sharathava** [comment]
Okay, So firefox would track the mouse move outside the window.
Is there a way I can fix this for IE and chrome? Or is it a limitation?

**Comment by adriancabouli** [comment]
this.createNipple =function(evt) {
		
		////////////////////////////////////////////////////////	      
		////////////////////////////////////////////////////////
		///JOYSTIC // CONTROLES
		////////////////////////////////////////////////////////	
		////////////////////////////////////////////////////////	
		
		var s = function (sel) {   return document.querySelector(sel); };
		var sId = function (sel) { return document.getElementById(sel); };
		
		var joysticks = {
			static: {
				zone: s('.zone.static'),
				mode: 'static',
				position: {right: '80px', bottom: '80px'},
				color: 'rgba(97, 97, 97, 0.79)'
			}
		};
		
		joystick;
					
		var type = typeof evt === 'string' ?
			evt : evt.target.getAttribute('data-type');
		joystick = nipplejs.create(joysticks[type]);
		gameParent.TheJoystick=joystick;
		this.bindNipple();
	}

**Comment by adriancabouli** [comment]
touchcancel event it fix the problem!, 

$(document).on('touchcancel', function(event) {
   REMOVE_AND_CREATE_JOYSTIC()	// or whatever... 
});
