### ISSUE TITLE
How to delicately remove the nipple?

### ISSUE THREAD

**Issue by JSteunou** [yoannmoinet/nipplejs#6]
First, kudos for this tool!

I have a need to create 2 nipples, on the same el, the second after shutting down the first, with some other parameters. Or maybe there is a way to change a nipple size after initialisation?

**Comment by yoannmoinet** [comment]
Thanks a lot !

I'm not sure to understand your setup.

You have an element, on which you'd like to instantiate 2 nipples. 

Each one activated via multitouch I guess? 1 finger, 1 nipple. (:smile: this name makes some funny conversation...)

If you need to create 2 nipples on the same element, maybe you could create two zones inside this element, and then create one nipple on each zone?

Be aware that there are still bugs with the multitouch, that I have to tackle.

**Comment by JSteunou** [comment]
That's not my issue sorry I did not explain it very well.

I have 2 needs, both I though could be resolved by destroying the instance.

1/ I create a nipple instance on an element but after a certain user action I need to remove that instance. Totally. Forever.
2/ On another case, totally different from the 1st, I create a nipple instance but after a certain event I need to increase it's size. Which I managed differently by updating the options.size. I did not know that updating options after the instance was creating works, that's why I though about destroy / re-create.

**Comment by yoannmoinet** [comment]
Ok, that's a fair point.
I'll push this into the milestone and find a way to deal with this.

Instances will be more explicit and controllable.

**Comment by JSteunou** [comment]
Thank you :)

**Comment by JSteunou** [comment]
@yoannmoinet I just tested your 0.4.x release, I'm sorry but issue 2/ is worse with it :(

To sum it up

* I create a joystick (which is now a manager) with a specified size
* Some times the size is not correct because other things happens and I need to set a new size.
* With 0.3.0 I just had to update joystick.options.size and it worked
* With 0.4.0 I do not have access to size so I call `.off` on old manager and create a new one with the new size.
* Kitten dies: nipple show me a force `Infinity`. I suppose this was because sometimes my first size is `0`. But since I create a new manager with a new correct size (like 600), why on earth the old size would influence the new manager (and new nipples).

**Comment by JSteunou** [comment]
Fond a tail: old manager is still bind to move events. The same old manager that have size to 0. How can I cleanly destroy the manager so all events are unbind?

**Comment by yoannmoinet** [comment]
If you need to dynamicly update the size options on the manager we could add its `nippleOptions` to its exported signature.

Would this fix your issue? At least we'd go back to where we were in the `0.3.0`. And you'd be able to modify any new nipple instanciated.

What do you think?

We still need your `.destroy()` method though. It's a great feature.
