### ISSUE TITLE
Unable to scale up distance

### ISSUE THREAD

**Issue by LinuxCircle** [yoannmoinet/nipplejs#60]
Hi I need a more precise distance, to control my RC car with this.
It works ok with out of 100 distance, but for turning left and right I need 10x more accuracy, because the distance is linked to the angle of the direction of the car.
Is there a way to modify it to show value between 0-1000 instead of 0-100? 

I cannot simply multiply the distance by 10, because when it maps to servo angle, it will skip some degrees of the angles. The servo works on the frequency  of PWM between 1000-2000. 1500 is mid. 1000 is total left. 2000 is right. 
So when I map it, it goes like this....
1 = 10
2 = 20
3 = 30

I want to be able to go into more angle instead of jumping 10 steps all the time.

Is there anything I can modify to achieve it?

**Comment by yoannmoinet** [comment]
What's your code to get this kind of 0.1 precision?

The precision of pretty much all events is like 0.0000000000001, so you should be ok with this.

From the demo, you can see the force and the angle events that are very precise.

<img width="240" alt="screen shot 2017-11-27 at 18 30 36" src="https://user-images.githubusercontent.com/597828/33280053-1e15f6a4-d3a1-11e7-957d-c3dd7f8a0d6c.png">

**Comment by yoannmoinet** [comment]
Closing this as no more answer from you @LinuxCircle .

Feel free to re-open if needed.
