### ISSUE TITLE
nipplejs get stuck in iphone when switch app

### ISSUE THREAD

**Issue by adriancabouli** [yoannmoinet/nipplejs#61]
hi, i am having troubles with the plugin. I made a game, and use the nipplejs like a joystick. When, (by mistake) the user switch the app to another, or try to, and in that moment is moving the joystick, when returns back to the app, the joystick became stuck in the last position that it was. And then is no way back, it always keep like that. I made a code that if i leave completly the app, (it calls in jquery VisibilityHidden) i remove nipplejs and create new instance. But the problem appear if i switch to another app and return back instantly to my game, or also when the apps are showing in "select app to switch" in iphone, and i am keeping moving the joystick. It happens a lot with iphone x cause the status bar in landscape mode is always visible and close to the joystick, so is probbably that the bug problem happen more than once. Thanks!

**Comment by adriancabouli** [comment]
i also made an easy test to reproduce the error. If a alert("bla bla") box appear when i am moving the joystick it will get stuck too! (always in iphone i am testing). thks!!

**Comment by yoannmoinet** [comment]
I'll have a look as soon as I have time.

PR are more than welcome.

**Comment by adriancabouli** [comment]
i just found the solution:
touchcancel event it fix the problem
    El lunes, 27 de noviembre de 2017 14:34:35 ART, Yoann Moinet <notifications@github.com> escribió:  
 
 
I'll have a look as soon as I have time.

PR are more than welcome.

**Comment by adriancabouli** [comment]
touchcancel event it fix the problem!, 

$(document).on('touchcancel', function(event) {
   REMOVE_AND_CREATE_JOYSTIC()	// or whatever... 
});

**Comment by yoannmoinet** [comment]
I'll be damned... did you test it in every issues you've answered?
Thanks a lot for finding this out anyway.
I'll think of a solution to add this in the library.

**Comment by adriancabouli** [comment]
Hi! It was a pleassure! your pluging rocks!
At léast in my case in plugin static mode all the issues that i answered become fixed with touchcancel event. And for the user experience is imperceptible when you destroy and create new instance (in static of course)

Enviado desde mi iPhone

**Comment by adriancabouli** [comment]
HERE for iphone 7 and > (iphone x compatible), is my game using the plugin!, in the new release the error is fixed. 
It would be great if my game is spread! Thks in advance!

https://itunes.apple.com/us/app/partners/id1294121944?l=es&ls=1&mt=8

**Comment by tonyka** [comment]
@adriancabouli this works better for me:
```
$(window).on('touchcancel', function(e) {
    nipple.processOnEnd(e);
})
```
