### ISSUE TITLE
Static mode nipple in 'position: fixed' zone is broken by scrolling.

### ISSUE THREAD

**Issue by micah-boswell-aquabotix** [yoannmoinet/nipplejs#65]
Does not account for scroll here: https://github.com/yoannmoinet/nipplejs/blob/0c982ce1fe25ae6d96a0765d48f0f348a030f960/src/collection.js#L349
And it does need to account for scroll in the case that the zone element has 'position' css set to 'fixed' (in which case nipple.position is wrong).

**Comment by yoannmoinet** [comment]
Hm... that'll be an interesting fix.

Thanks for reporting.

**Comment by yoannmoinet** [comment]
I'll need an example where the issue occurs.
Until then, I'm closing this.
