### ISSUE TITLE
Allow having a permanently shown (faded out) joystick

### ISSUE THREAD

**Issue by yoannmoinet** [yoannmoinet/nipplejs#7]
If the user releases the joystick, we should be able to have a persistent joystick shown.
Instead of having it disappeared each time.

- faded element when released and full opacity when pressed.
- the tip should go back to its initial position when released.
- when re-pressed in the joystick's zone, directly move the tip and let the back at its position.

**Comment by Antariano** [comment]
I'd be very interested in this functionality. :+1:

**Comment by yoannmoinet** [comment]
Thank you for the feedback @Antariano.
Since you're interested in this, what do you think about this ?

I was thinking about 3 different modes possible. 
**`dynamic`**
> press -> appears, release -> disappears. 
> Gets replaced each new press and does not compute direction on start.
> The same as right now.
> Multitouch possible.

**`semi`**
> press -> appears, release -> fade-out. 
> Gets replaced if new press is outside the joystick zone and does not compute direction on start.
> Computes direction if pressed in the joystick zone.
> Multitouch possible outside the joystick zone.

**`static`**
> always on, static position, each press computes a new direction.
> No multitouch.

What would be your preferred workflow?

**Comment by Antariano** [comment]
My personal usage would be a single nipple that should not change position. If I understand you correctly this would be `static`?

However I can see other developers having different needs. 

Just so I understand this correctly, when you say "disappears" you mean in a disabled, still visible state?

**Comment by yoannmoinet** [comment]
Very good, indeed your usage would be in a `static` mode.

The joystick would never disappear and would fade out on release. Not invisible, just more transparent than normal.

When I say 'disappears' in the previous modes explanation, it means that the joystick totally disappears, it becomes invisible (alpha 0) and its DOM element gets totally removed from the DOM.

It will never happen in the `static` mode though.

I would add a fourth mode `invisible` to also fix #8 with a streamlined api.

**Comment by yoannmoinet** [comment]
fixed by 347feaaa38cd4e16f603dfe61580b15a1f53e70b

**Comment by Antariano** [comment]
Awesome, thank you so much for the rapid update! 

However I'm noticing a positioning issue when the nipple is moved from it's original position while in static mode, I'll get you some more info... please hold...

**Comment by Antariano** [comment]
Yep!
To reproduce, just go to your demo on http://yoannmoinet.github.io/nipplejs
and move the `<div class="zone" id="static">` down a bit with e.g. `top: 200px`, 
then try to move (wiggle?) the nipple control. It'll try to calculate the position from the old values.

**Comment by yoannmoinet** [comment]
Indeed. 
Maybe I could reinit the `this.box` values at each touch-start. I'll look into this.
Because it might create unpleasant situations on edge cases.

Thanks for reporting this. :+1:
