### ISSUE TITLE
Does not work directly on video element

### ISSUE THREAD

**Issue by elmarti** [yoannmoinet/nipplejs#71]
In this instance, the joystick triggers, but does not show when `zone` is an `HTMLMediaElement`, nice workaround is to wrap the video in a div and use that with 100% height/width set on the video. 

I may have a look into if I have time in the future, but as it stands I thought it would be worth posting the above for anyone who gets into my position.

**Comment by yoannmoinet** [comment]
Thank you for reporting this.
I'll have a look too when I have some time.

**Comment by yoannmoinet** [comment]
Media tags are not container tags. So it's fair to not consider this as a bug or an issue.

You should wrap your media in a div, and use that div as a container.

**Comment by elmarti** [comment]
I'm no longer involved in the project using this. I agree with you, but maybe the documentation should be explicit about this as a typical user will not be aware of/care what NippleJS does at the DOM level.
