### ISSUE TITLE
Click event

### ISSUE THREAD

**Issue by chukwu** [yoannmoinet/nipplejs#73]
What are the chances of getting a **click event listener** just like a real joystick? Atleast on the **static mode**. Joystick isn't much about moving around. Click is a very important part of a joystick simulation.

Can you include a position X and position Y minimum and maximum. Current values differs vastly depending on the position of Zone container. I think i can add a function to fix the positions. Most importantly, is the click event on the static mode atleast.

This library is the best out there but without this Two features, it is not usable for me.

Other joystick libraries can easily have a click event but this library

**Comment by yoannmoinet** [comment]
I'm not sure I do understand your request.

Do you mean if I only press down and up immediately?
What would be the use case of doing this on a virtual joystick?

**Comment by chukwu** [comment]
Im working on project that simulates a real iot joystick. Joysticks have a click-like action when you hold down. This plugin does not support it

**Comment by yoannmoinet** [comment]
You should be able to easily  implement this from outside the library, and in my humble opinion, you should do it this way.

I think I might miss the point of having this mechanic inside the core of the lib.

If you still think that this should be implemented from the library stand-point, feel free to submit a PR, I'll gladly review it.

Thank you very much for your interest, I'm closing this.
