### ISSUE TITLE
joystick breaking when opening notification panel

### ISSUE THREAD

**Issue by wbelhomsi** [yoannmoinet/nipplejs#75]
Thanks for the great plugin.. I'm working on a cordova project (android) and using your plugin as my primary joystick.. If you move the joystick with one hand and open the notification panel with the other, the joystick will freeze and stop working.. can you please check it out? Thanks!

**Comment by wbelhomsi** [comment]
Ok so i noticed there is an update.. ill update and try it again today and come back in case it didn't work

**Comment by yoannmoinet** [comment]
The update might be fixing this specific behavior.

It implements a better handling of the cancel event which should be specifically tested by this usecase.

Please, keep us updated!

**Comment by wbelhomsi** [comment]
0.7.1 fixed the issue!
Thanks yoan
