### ISSUE TITLE
"threshold is no longer exceeded" event?

### ISSUE THREAD

**Issue by rherrajan** [yoannmoinet/nipplejs#76]
Is there some kind of way to listen to a removal of state "plain:up" (when the threshold is no longer exceeded)?
For example when the user changes from up to right than I would like to know that he doesn't press up any more.

**Comment by yoannmoinet** [comment]
I think this can be implemented from outside the library.

Simply keep track of the previous `plain` event triggered, if a new one is triggered you'll know that the other one isn't active anymore.

If there are any strong blockers, feel free to re-open.
