### ISSUE TITLE
Relative value

### ISSUE THREAD

**Issue by grinmax** [yoannmoinet/nipplejs#77]
@yoannmoinet Hi, tell me please, how i can use "vw" instead "px". I want can scale nipple for some devices. Thanks!

**Comment by yoannmoinet** [comment]
A very simple google search bring me to [this](https://stackoverflow.com/questions/28295072/how-can-i-convert-px-to-vw-in-javascript).

Hope that helps.

**Comment by grinmax** [comment]
@yoannmoinet thanks, but I'm trying to replace 'px' with 'vw' in your js-code.
Styles work well http://joxi.ru/E2py9xMT94aOPA?d=1, but the position http://joxi.ru/Dr8BO7oC4JzkL2?d=1 does not work, as I'm used to, the nipple is very sensitive when moving. Can you help me with this? Replace the 'px' with "vw" and see what happens. Thanks!
