### ISSUE TITLE
Abut issue #77

### ISSUE THREAD

**Issue by grinmax** [yoannmoinet/nipplejs#78]
@yoannmoinet thanks, but I'm trying to replace 'px' with 'vw' in your js-code.
Styles work well http://joxi.ru/E2py9xMT94aOPA?d=1, but the position http://joxi.ru/Dr8BO7oC4JzkL2?d=1 does not work, as I'm used to, the nipple is very sensitive when moving. Can you help me with this? Replace the 'px' with "vw" and see what happens. Thanks!

**Comment by yoannmoinet** [comment]
I've already shared with you what you needed to achieve what you're trying to do.

Please stop opening issues for something you should ask on StackOverflow.
This is not an issue with my library.

If you need `vw` instead of `px`, fork the repo and do the conversion.

Thank you.
