### ISSUE TITLE
Don't understand in the Documentation how we access the joystick instance

### ISSUE THREAD

**Issue by Aarbel** [yoannmoinet/nipplejs#81]
Hi @yoannmoinet, thanks a lot for this very clean library.

One detail : i don't really understand what is the `joystick` instance in your documentation, and how to access it.

- It's not inside `manager`
- When we create a `manager` we don't know how the inner joysticks will be named
- I case we use two or more joysticks, We don't know if we should create a manager with multiple joystick inside, or if we create multiple managers with one joystick inside Each

All the rest of the doc is absolutely clear !

**Comment by yoannmoinet** [comment]
Hi @Aarbel, I agree, it's not that clear.

If you look at the [Events](https://github.com/yoannmoinet/nipplejs#events) part of the doc, you'll find an example showing how to get an instance on creation.

This is one way of getting an instance.

The [manager](https://github.com/yoannmoinet/nipplejs#nipplejs-instance-manager) also have an array of ids in `manager.ids`. 
You can then use [`manager.get(joystickId)`](https://github.com/yoannmoinet/nipplejs#managergetidentifier) to get any instance you'd like.

Hope this helps.
Cheers!
