### ISSUE TITLE
Allow having custom elements for the joystick

### ISSUE THREAD

**Issue by yoannmoinet** [yoannmoinet/nipplejs#9]
If needed the developer should be able to assign himself his elements to the joystick.
And provides some kind of template for it.

**Comment by ablakey** [comment]
Ran into a case on the factory floor where I could benefit from this.  If not custom elements, at the very least custom CSS for the inner and outer circles.  For example, I need to do high contrast view, which involves having a solid thick yellow border and no background.

**Comment by yoannmoinet** [comment]
@ablakey you definitely can do some stuff with CSS in the current implementation.

Because you have access to [the element of the joystick as needed](https://github.com/yoannmoinet/nipplejs#joystickel) and it's a very basic DOM element you can easily customize via CSS as every part of it has a specific class.

**Comment by ablakey** [comment]
Yup, that's what I discovered and am doing. However it feels kludgy because it applies a class, which I have to remove or override with !important.  

The way `color` is an attribute passable into the component, it would be nice to be able to pass in classnames to override or extend the defaults.

But you're right. I've discovered that there is an escape hatch to start mucking about with the styles.

**Comment by Latence132** [comment]
Hi yoannmoinet,
Firstly thank's you very much for nipplejs, it is awesmone! 👍 

I don't manage to change the display of the joystick. I tried to change the front joystick with an image 
![button](https://user-images.githubusercontent.com/30188846/41902971-ff47e8f6-7934-11e8-9bd5-1f8997a7a0c4.png)

 I am on 
- nipplejs@0.7.1
- nuxt-edge@2.0.0-25481399.feabdca + vuejs
- vuetify@1.0.19

The HTML code is :

    <div id="joystick1" class="mx-auto" data-v-e2f21d04="" style="touch-action: none;">

      <div class="nipple collection_0" id="nipple_0_0" style="position: absolute; opacity: 0.5; display: block; z-index: 999; transition: opacity 250ms; left: 6%;">

        <div class="back" style="position: absolute; display: block; width: 100px; height: 100px; margin-left: -50px; margin-top: -50px; background: red; opacity: 0.5; border-radius: 50%;"></div>

        <div class="front" style="width: 50px; height: 50px; position: absolute; display: block; margin-left: -25px; margin-top: -25px; background: red; opacity: 0.5; border-radius: 50%; left: 0px; top: 0px;"></div>

      </div>
    </div>


![image](https://user-images.githubusercontent.com/30188846/41903472-4b2639de-7936-11e8-9adc-f803ce21fe71.png)


The CSS generated to change the front is :
    .front[data-v-e2f21d04] {
      background-image: url(/_nuxt/img/button.8605029.png) !important;
    }
![image](https://user-images.githubusercontent.com/30188846/41903564-8b310784-7936-11e8-8bae-d09fbfb2e0c8.png)

**Comment by yoannmoinet** [comment]
@Latence132 hey there.

I think your CSS selector is wrong, can you try this instead?

```css
div[data-v-e2f21d04] .front {
    background-image: url(/_nuxt/img/button.8605029.png) !important;
}
```

**Comment by Latence132** [comment]
It work !
I just have to ajust my CSS,

thank you :)

**Comment by yoannmoinet** [comment]
no need to track this. I'm closing.
