### ISSUE TITLE
Joystick gets stuck on status bar in iOS

### ISSUE THREAD

**Issue by Steckdoserich** [yoannmoinet/nipplejs#93]
On all of my Apple products (iPhone SE, iPhone 7, Mac mini) the joystick gets stuck. What you simply have to do is to drag the joystick to the top menu/status bar and then release the finger/left click. After that the joystick gets stuck in the last position. To release it you have to start a new touch/click event.

Did anyone else experienced this problem? Is there a workaround?

**Comment by yoannmoinet** [comment]
Did you get this behavior in one of the example we have?

Because I could not reproduce the issue on iOS Simulator, which is the only way I have to test iOS devices.

Please reopen with some testable code.
Thank you.

**Comment by Steckdoserich** [comment]
In the gif below you can see what I mean. This behavior leads to a stucked stick on some of my mobile devices.
![ios_nipplejs](https://user-images.githubusercontent.com/14337752/50388441-e853ed00-0716-11e9-9359-e185a907e853.gif)
If I can support you with any information, then let me know.

**Comment by yoannmoinet** [comment]
Also, what kind of iPad, iOS do you use?

**Comment by Steckdoserich** [comment]
Thanks @yoannmoinet for having a look into it!
The gif was in the safari (12.0.2) on my Mac (Version 10.14.2).

My first experience with this bug was in my App. I'm currently using your plugin to bring a joystick into my Cordova App. My first step was to check if the problem was on my side. So I just build a Cordova App with your third test (index3.html) in it. As you can see in the gif below, this bug can occur on mobile devices as well. 
![bildschirmaufnahme 2018-12-24 um 12 37 11](https://user-images.githubusercontent.com/14337752/50398696-e7a07280-0779-11e9-9a80-115f6617d770.gif)
This has been tested on my iPhone SE (iOS 12.1) and iPhone 7 (iOS 12.1). While the gif is recorded on an iPhone SE 12.1 Simulator, because I can display my touch events.

**Comment by Steckdoserich** [comment]
@yoannmoinet I just found out that a touchend event doesn't get called in iOS when you leave the screen over the statusbar. Therefore the pageY value of the touchmove event is going negative. I found the solution over here: https://stackoverflow.com/a/37434902/1754625
