### ISSUE TITLE
[BUG] Building with Ionic Framework and NippleJS (Angular/Typescript Issues)

### ISSUE THREAD

**Issue by bhoffman314** [yoannmoinet/nipplejs#95]
**Describe the bug**
When building with Ionic framework some problems are flagged as TypeScript errors even though they work properly on a web client. These issues will completely remove the ability to build an Ionic app to a platform other than web. I found work-arounds for them and figured documentation here may be helpful.

**To Reproduce**

- Create an Ionic project and use a Nipple joystick
- Build for Android with `ionic cordova build android` 
- Typescript errors will appear

![image](https://user-images.githubusercontent.com/25619718/50668033-5c8d5c80-0f71-11e9-8af8-2402287a1527.png)
This error will show up for the first three arrays declared here. Declaring them as type any (as seen in the last line) will fix the problem.

Declaring the mode in the options object causes a type error saying type string is not assignable to type `"'dynamic' | 'semi' | 'static'".` If you change mode in index.d.ts to read: `mode?: string;` the error disappears and the joystick still functions as expected (at least in static mode, I did not try any others).

**Expected behavior**
Project compiles as expected

**Desktop (please complete the following information):**
Ubuntu - Firefox Quantum - Ionic Framework
node version 10.14.2
npm version 6.4.1
ionic version 4.5.0
cordova version 8.1.2

**Comment by nielsswinkels** [comment]
Got this error when updating to @ionic-native/core 5.0.0 (coming from 4.7.0 where it worked fine)

**Comment by iodev** [comment]
fixed in commit 4f1bdbdd8dcd60e549adb830ab2866d99d22c94a

**Comment by yoannmoinet** [comment]
has been published in `0.8.2`.
