### ISSUE TITLE
[FEAT] Include TypeScript definitions in npm

### ISSUE THREAD

**Issue by sjml** [yoannmoinet/nipplejs#99]
**Is your feature request related to a problem? Please describe.**
The project has TypeScript definitions, and they're pointed to in the `package.json` file, but not in the uploaded version to npm. 

**Describe the solution you'd like**
Add `types/index.d.ts` to the files that get uploaded to npm. 

**Describe alternatives you've considered**
The type files can get manually added to a project, but since they are officially part of the repo anyway, and the package file is trying to claim they are there, it helps the compiler to have them there by default.

**Comment by sjml** [comment]
Just made a pull request that should handle this.

**Comment by yoannmoinet** [comment]
Thanks @sjml !
